// <auto-generated />
using Day_1.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Day_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251020114315_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Day_1.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Loc")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("DepartmentName");

                    b.HasKey("Id");

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Loc = "Ahmed Ali",
                            Name = "Backend "
                        },
                        new
                        {
                            Id = 2,
                            Loc = "Mona Salah",
                            Name = "Frontend "
                        },
                        new
                        {
                            Id = 3,
                            Loc = "Omar Khalid",
                            Name = "FullStack "
                        },
                        new
                        {
                            Id = 4,
                            Loc = "Sara Ahmed",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 5,
                            Loc = "Ali Hassan",
                            Name = "Mobile "
                        },
                        new
                        {
                            Id = 6,
                            Loc = "Nour Mahmoud",
                            Name = "Data Science"
                        });
                });

            modelBuilder.Entity("Day_1.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasColumnName("Address");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("FullName");

                    b.Property<int>("age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Alex",
                            DepartmentId = 1,
                            FullName = "Ahmed Mohamed",
                            age = 18
                        },
                        new
                        {
                            Id = 2,
                            Address = "Mansura",
                            DepartmentId = 5,
                            FullName = "Mohamed Ali",
                            age = 22
                        },
                        new
                        {
                            Id = 3,
                            Address = "Gize",
                            DepartmentId = 2,
                            FullName = "Hana Magdy",
                            age = 19
                        },
                        new
                        {
                            Id = 4,
                            Address = "Cairo",
                            DepartmentId = 6,
                            FullName = "Omar Khaled",
                            age = 23
                        },
                        new
                        {
                            Id = 5,
                            Address = "Suez",
                            DepartmentId = 4,
                            FullName = "Khaled Mahmoud",
                            age = 22
                        },
                        new
                        {
                            Id = 6,
                            Address = "Alex",
                            DepartmentId = 3,
                            FullName = "Nadin Hossam",
                            age = 21
                        });
                });

            modelBuilder.Entity("Day_1.Models.Student", b =>
                {
                    b.HasOne("Day_1.Models.Department", "Department")
                        .WithMany("Students")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Day_1.Models.Department", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
